services:
  ms-tc-discovery:
    build: ./ms-tc-discovery
    container_name: ms-tc-discovery
    ports:
      - '8761:8761'
    expose:
      - '8761'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]

  ms-tc-config:
    build: ./ms-tc-config
    container_name: ms-tc-config
    ports:
      - '9999:9999'
    expose:
      - '9999'
#    environment:
#      MS_TC_DISCOVERY_URL : http://ms-tc-discovery:8761/eureka
#    depends_on:
#      ms-tc-discovery:
#        condition: service_healthy
