server:
  port: 8083

spring:
  application:
    name: ms-tc-activity

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: youness
    password: admin

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql