server:
  port: 8082

spring:
  application:
    name: ms-tc-activity

  datasource:
    url: jdbc:postgresql://localhost:5432/activity
    username: youness
    password: admin

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
