spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]' :
            allowedOrigins: "*"
            allowed-headers: *
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE